### ISSUE TITLE
Can this project run on the Intel UHD Graphics 630 gpu ?

### ISSUE THREAD

**Issue by yuxiao-ash** [kennyalive/vulkan-raytracing#1]
I clone this project on my win10 PC and I got this result:
![image](https://user-images.githubusercontent.com/35222407/148940222-f5a850e4-53dd-4df6-88ca-1a4b4cca378e.png)
My vulkan sdk is 1.2.198.1, is the problem above caused by the gpu type ?

**Comment by kennyalive** [comment]
Yes, that means that the GPU does not support raytracing (or drivers are old but I don't think that's the case, intel chips probably don't have support).
